-- ─────────────────────────────────────────────────────────────────────────────
-- ONBOARDING DRAFTS — Phase 3 (AI Auto-Config)
--
-- Stores draft configurations generated by the AI onboarding pipeline.
-- A draft is created when an internal admin runs "Auto-config" from a URL.
-- It stays in 'draft' status until the admin reviews, edits, and saves it.
-- On save (commitDraftToDb), a real client record is created in the clients table.
--
-- Safe to run multiple times: CREATE TABLE IF NOT EXISTS.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS onboarding_drafts (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_by      text,                -- portal user email who triggered analysis
  source_url      text NOT NULL,       -- the URL that was analyzed

  -- Lifecycle
  status          text NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'saved', 'discarded')),

  -- Extracted / editable draft fields (jsonb so the schema stays flexible)
  draft_client    jsonb NOT NULL DEFAULT '{}',
  -- { name, slug, industry, support_phone, support_email, address, timezone,
  --   website_url, services[], hours }

  draft_bot       jsonb NOT NULL DEFAULT '{}',
  -- { bot_name, tone, opener_text }

  draft_booking   jsonb NOT NULL DEFAULT '{}',
  -- { booking_mode, booking_link, booking_platform }

  -- Raw extraction output stored for debugging / re-review
  extracted_facts jsonb NOT NULL DEFAULT '{}',

  -- Per-field confidence: { name: "high"|"medium"|"low", booking_mode: ..., ... }
  confidence      jsonb NOT NULL DEFAULT '{}',

  -- Array of warning strings shown in the review UI
  warnings        jsonb NOT NULL DEFAULT '[]',

  -- How many pages were crawled during analysis
  pages_crawled   integer NOT NULL DEFAULT 0,

  -- If a client was created from this draft, store its ID
  committed_client_id  text REFERENCES clients(id) ON DELETE SET NULL,

  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Index for listing drafts by status
CREATE INDEX IF NOT EXISTS onboarding_drafts_status_idx
  ON onboarding_drafts (status, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- Verify
-- ─────────────────────────────────────────────────────────────────────────────
-- SELECT id, source_url, status, pages_crawled, created_at
-- FROM onboarding_drafts
-- ORDER BY created_at DESC
-- LIMIT 20;
